version: 2
jobs:
  build:
    docker:
      - image: suculent/platformio-docker-build
    steps:
      - checkout
      - run: pio ci --board=esp32dev examples/CLI/ --lib src/
      - run: pio ci --board=esp32dev examples/SerialLogging/ --lib src/
      - run: pio ci --board=esp32dev examples/UnitsConversion/ --lib src/
      - run: pio ci --board=esp32dev examples/Values/ --lib src/
      - run: pio ci --board=esp32dev examples/TimerSimple/ --lib src/
      - run: pio ci --board=esp32dev examples/TimerCallbacks/ --lib src/
