version: 2
jobs:
  build:
    docker:
      - image: suculent/platformio-docker-build
    steps:
      - checkout
      - run: pio upgrade
      - run: pio ci --board=esp32dev examples/CLI_Basic/ --lib src/
      - run: pio ci --board=esp32dev examples/CLI_Continuous/ --lib src/
      - run: pio ci --board=esp32dev examples/SerialLogging/ --lib src/
      - run: pio ci --board=esp32dev examples/UnitsConversion/ --lib src/
      - run: pio ci --board=esp32dev examples/Values/ --lib src/
      - run: pio ci --board=esp32dev examples/Timer_Basic/ --lib src/
      - run: pio ci --board=esp32dev examples/Timer_Callbacks/ --lib src/
      - run: pio ci --board=esp32dev examples/HTTPPackage/ --lib src/
